export const SEND_MESSAGE_DELAY_AFTER_SECONDS = 5;
export const CHECK_DISK_ALERT_AFTER_MINUTES = 60 * (60 * 1000); // hour
export const CHECK_DISK_WARN_GB_LOW_ALERT_REPEAT_MINUTES = 15 * (60 * 1000); // 15 min
export const CHECK_DISK_WARN_GB_LOW_THRESHOLD = 7;
export const PIN_MESSAGE_UPDATE_FIRST_DELAY_SECONDS = 2;
